# Generated by Django 3.2.9 on 2021-12-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211206_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(height_field=400, null=True, upload_to='', verbose_name='Картинка продукта', width_field=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', verbose_name='Описание продукта'),
        ),
    ]
